name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC (adjust as needed)
  workflow_dispatch: # lets you run it manually too

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Upload YouTube short
        run: |
          python upload/upload_to_youtube.py
